[package]
name = "ElasticEmail"
version = "4.2.0"
authors = ["Elastic Email <support@elasticemail.com>"]
description = "Official Rust SDK for the Elastic Email REST API v4"
license = "MIT"
edition = "2021"
repository = "https://github.com/ElasticEmail/elasticemail-rust"
homepage = "https://elasticemail.com/email-api"
documentation = "https://docs.rs/ElasticEmail"
readme = "README.md"
keywords = ["elasticemail", "email", "smtp", "transactional", "api"]
categories = ["api-bindings", "email", "web-programming::http-client"]
exclude = [".github/", ".travis.yml"]

[dependencies]
serde = { version = "^1.0", features = ["derive"] }
serde_with = { version = "^3.8", default-features = false, features = ["base64", "std", "macros"] }
serde_json = "^1.0"
serde_repr = "^0.1"
url = "^2.5"
uuid = { version = "^1.8", features = ["serde", "v4"] }
reqwest = { version = "^0.12", features = ["json", "multipart"] }
