/*
 * Elastic Email REST API
 *
 * This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    To start using this API, you will need your Access Token (available <a href=\"https://elasticemail.com/account#/settings/new/manage-api\">here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    This is the documentation for REST API. If you’d like to read our legacy documentation regarding Web API v2 click <a href=\"https://api.elasticemail.com/public/help\">here</a>.
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@elasticemail.com
 * Generated by: https://openapi-generator.tech
 */

/// CampaignOptions : Different send options for a Campaign



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CampaignOptions {
    /// How to order email delivery - by recipients' engagement score or by the time they open the most of the emails that were sent to them
    #[serde(rename = "DeliveryOptimization", skip_serializing_if = "Option::is_none")]
    pub delivery_optimization: Option<crate::models::DeliveryOptimizationType>,
    /// Should the opens be tracked? If no value has been provided, Account's default setting will be used.
    #[serde(rename = "TrackOpens", skip_serializing_if = "Option::is_none")]
    pub track_opens: Option<bool>,
    /// Should the clicks be tracked? If no value has been provided, Account's default setting will be used.
    #[serde(rename = "TrackClicks", skip_serializing_if = "Option::is_none")]
    pub track_clicks: Option<bool>,
    /// Date when this Campaign is scheduled to be sent on
    #[serde(rename = "ScheduleFor", skip_serializing_if = "Option::is_none")]
    pub schedule_for: Option<String>,
    /// Optional options for A/X split campaigns. Will be ignored if only one template content was provided
    #[serde(rename = "SplitOptions", skip_serializing_if = "Option::is_none")]
    pub split_options: Option<crate::models::SplitOptions>,
}

impl CampaignOptions {
    /// Different send options for a Campaign
    pub fn new() -> CampaignOptions {
        CampaignOptions {
            delivery_optimization: None,
            track_opens: None,
            track_clicks: None,
            schedule_for: None,
            split_options: None,
        }
    }
}


