/*
 * Elastic Email REST API
 *
 * This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    To start using this API, you will need your Access Token (available <a href=\"https://elasticemail.com/account#/settings/new/manage-api\">here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    This is the documentation for REST API. If you’d like to read our legacy documentation regarding Web API v2 click <a href=\"https://api.elasticemail.com/public/help\">here</a>.
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@elasticemail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConsentData {
    /// IP address of consent to send this contact(s) your email. If not provided your current public IP address is used for consent.
    #[serde(rename = "ConsentIP", skip_serializing_if = "Option::is_none")]
    pub consent_ip: Option<String>,
    /// Date of consent to send this contact(s) your email. If not provided current date is used for consent.
    #[serde(rename = "ConsentDate", skip_serializing_if = "Option::is_none")]
    pub consent_date: Option<String>,
    /// Does the contant consent to have their tracking data stored.
    #[serde(rename = "ConsentTracking", skip_serializing_if = "Option::is_none")]
    pub consent_tracking: Option<crate::models::ConsentTracking>,
}

impl ConsentData {
    pub fn new() -> ConsentData {
        ConsentData {
            consent_ip: None,
            consent_date: None,
            consent_tracking: None,
        }
    }
}


