/*
 * Elastic Email REST API
 *
 * This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    The API has a limit of 20 concurrent connections and a hard timeout of 600 seconds per request.    To start using this API, you will need your Access Token (available <a target=\"_blank\" href=\"https://app.elasticemail.com/marketing/settings/new/manage-api\">here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    Downloadable library clients can be found in our Github repository <a target=\"_blank\" href=\"https://github.com/ElasticEmail?tab=repositories&q=%22rest+api%22+in%3Areadme\">here</a>
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@elasticemail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ConsentData {
    /// IP address of consent to send this contact(s) your email. If not provided your current public IP address is used for consent.
    #[serde(rename = "ConsentIP", skip_serializing_if = "Option::is_none")]
    pub consent_ip: Option<String>,
    /// Date of consent to send this contact(s) your email. If not provided current date is used for consent.
    #[serde(rename = "ConsentDate", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub consent_date: Option<Option<String>>,
    #[serde(rename = "ConsentTracking", skip_serializing_if = "Option::is_none")]
    pub consent_tracking: Option<crate::models::ConsentTracking>,
}

impl ConsentData {
    pub fn new() -> ConsentData {
        ConsentData {
            consent_ip: None,
            consent_date: None,
            consent_tracking: None,
        }
    }
}


