/*
 * Elastic Email REST API
 *
 * This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    To start using this API, you will need your Access Token (available <a href=\"https://elasticemail.com/account#/settings/new/manage-api\">here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    This is the documentation for REST API. If you’d like to read our legacy documentation regarding Web API v2 click <a href=\"https://api.elasticemail.com/public/help\">here</a>.
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@elasticemail.com
 * Generated by: https://openapi-generator.tech
 */

/// Contact : Contact



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Contact {
    /// Proper email address.
    #[serde(rename = "Email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    /// Status of the given resource
    #[serde(rename = "Status", skip_serializing_if = "Option::is_none")]
    pub status: Option<crate::models::ContactStatus>,
    /// First name.
    #[serde(rename = "FirstName", skip_serializing_if = "Option::is_none")]
    pub first_name: Option<String>,
    /// Last name.
    #[serde(rename = "LastName", skip_serializing_if = "Option::is_none")]
    pub last_name: Option<String>,
    /// A key-value collection of custom contact fields which can be used in the system.
    #[serde(rename = "CustomFields", skip_serializing_if = "Option::is_none")]
    pub custom_fields: Option<::std::collections::HashMap<String, String>>,
    #[serde(rename = "Consent", skip_serializing_if = "Option::is_none")]
    pub consent: Option<crate::models::ConsentData>,
    /// From where was this contact added
    #[serde(rename = "Source", skip_serializing_if = "Option::is_none")]
    pub source: Option<crate::models::ContactSource>,
    /// Date of creation in YYYY-MM-DDThh:ii:ss format
    #[serde(rename = "DateAdded", skip_serializing_if = "Option::is_none")]
    pub date_added: Option<String>,
    /// Last change date
    #[serde(rename = "DateUpdated", skip_serializing_if = "Option::is_none")]
    pub date_updated: Option<String>,
    /// Date of last status change.
    #[serde(rename = "StatusChangeDate", skip_serializing_if = "Option::is_none")]
    pub status_change_date: Option<String>,
    /// Contact's email statistics and activity
    #[serde(rename = "Activity", skip_serializing_if = "Option::is_none")]
    pub activity: Option<crate::models::ContactActivity>,
}

impl Contact {
    /// Contact
    pub fn new() -> Contact {
        Contact {
            email: None,
            status: None,
            first_name: None,
            last_name: None,
            custom_fields: None,
            consent: None,
            source: None,
            date_added: None,
            date_updated: None,
            status_change_date: None,
            activity: None,
        }
    }
}


