/*
 * Elastic Email REST API
 *
 * This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    The API has a limit of 20 concurrent connections and a hard timeout of 600 seconds per request.    To start using this API, you will need your Access Token (available <a target=\"_blank\" href=\"https://app.elasticemail.com/marketing/settings/new/manage-api\">here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    Downloadable library clients can be found in our Github repository <a target=\"_blank\" href=\"https://github.com/ElasticEmail?tab=repositories&q=%22rest+api%22+in%3Areadme\">here</a>
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@elasticemail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ContactSource {
    #[serde(rename = "DeliveryApi")]
    DeliveryApi,
    #[serde(rename = "ManualInput")]
    ManualInput,
    #[serde(rename = "FileUpload")]
    FileUpload,
    #[serde(rename = "WebForm")]
    WebForm,
    #[serde(rename = "ContactApi")]
    ContactApi,
    #[serde(rename = "VerificationApi")]
    VerificationApi,
    #[serde(rename = "FileVerificationApi")]
    FileVerificationApi,

}

impl std::fmt::Display for ContactSource {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::DeliveryApi => write!(f, "DeliveryApi"),
            Self::ManualInput => write!(f, "ManualInput"),
            Self::FileUpload => write!(f, "FileUpload"),
            Self::WebForm => write!(f, "WebForm"),
            Self::ContactApi => write!(f, "ContactApi"),
            Self::VerificationApi => write!(f, "VerificationApi"),
            Self::FileVerificationApi => write!(f, "FileVerificationApi"),
        }
    }
}

impl Default for ContactSource {
    fn default() -> ContactSource {
        Self::DeliveryApi
    }
}

