/*
 * Elastic Email REST API
 *
 * This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    The API has a limit of 20 concurrent connections and a hard timeout of 600 seconds per request.    To start using this API, you will need your Access Token (available <a target='_blank' href='https://app.elasticemail.com/marketing/settings/new/manage-api'>here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    Downloadable library clients can be found in our Github repository <a target='_blank' href='https://github.com/ElasticEmail?tab=repositories&q=%22rest+api%22+in%3Areadme'>here</a>
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@elasticemail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DkimRecord : Content of the DKIM record to be added to DNS for the domain.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DkimRecord {
    #[serde(rename = "Selector", skip_serializing_if = "Option::is_none")]
    pub selector: Option<String>,
    #[serde(rename = "PublicKey", skip_serializing_if = "Option::is_none")]
    pub public_key: Option<String>,
    #[serde(rename = "HostName", skip_serializing_if = "Option::is_none")]
    pub host_name: Option<String>,
    #[serde(rename = "RecordValue", skip_serializing_if = "Option::is_none")]
    pub record_value: Option<String>,
    /// Name of selected domain.
    #[serde(rename = "Domain", skip_serializing_if = "Option::is_none")]
    pub domain: Option<String>,
}

impl DkimRecord {
    /// Content of the DKIM record to be added to DNS for the domain.
    pub fn new() -> DkimRecord {
        DkimRecord {
            selector: None,
            public_key: None,
            host_name: None,
            record_value: None,
            domain: None,
        }
    }
}

