/*
 * Elastic Email REST API
 *
 * This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    The API has a limit of 20 concurrent connections and a hard timeout of 600 seconds per request.    To start using this API, you will need your Access Token (available <a target=\"_blank\" href=\"https://app.elasticemail.com/marketing/settings/new/manage-api\">here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    Downloadable library clients can be found in our Github repository <a target=\"_blank\" href=\"https://github.com/ElasticEmail?tab=repositories&q=%22rest+api%22+in%3Areadme\">here</a>
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@elasticemail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EncodingType : Encoding type for the email headers
/// Encoding type for the email headers
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EncodingType {
    #[serde(rename = "UserProvided")]
    UserProvided,
    #[serde(rename = "None")]
    None,
    #[serde(rename = "Raw7bit")]
    Raw7bit,
    #[serde(rename = "Raw8bit")]
    Raw8bit,
    #[serde(rename = "QuotedPrintable")]
    QuotedPrintable,
    #[serde(rename = "Base64")]
    Base64,
    #[serde(rename = "Uue")]
    Uue,

}

impl std::fmt::Display for EncodingType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::UserProvided => write!(f, "UserProvided"),
            Self::None => write!(f, "None"),
            Self::Raw7bit => write!(f, "Raw7bit"),
            Self::Raw8bit => write!(f, "Raw8bit"),
            Self::QuotedPrintable => write!(f, "QuotedPrintable"),
            Self::Base64 => write!(f, "Base64"),
            Self::Uue => write!(f, "Uue"),
        }
    }
}

impl Default for EncodingType {
    fn default() -> EncodingType {
        Self::UserProvided
    }
}

