/*
 * Elastic Email REST API
 *
 * This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    The API has a limit of 20 concurrent connections and a hard timeout of 600 seconds per request.    To start using this API, you will need your Access Token (available <a target=\"_blank\" href=\"https://app.elasticemail.com/marketing/settings/new/manage-api\">here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    Downloadable library clients can be found in our Github repository <a target=\"_blank\" href=\"https://github.com/ElasticEmail?tab=repositories&q=%22rest+api%22+in%3Areadme\">here</a>
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@elasticemail.com
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum LogJobStatus {
    #[serde(rename = "All")]
    All,
    #[serde(rename = "ReadyToSend")]
    ReadyToSend,
    #[serde(rename = "WaitingToRetry")]
    WaitingToRetry,
    #[serde(rename = "Sending")]
    Sending,
    #[serde(rename = "Error")]
    Error,
    #[serde(rename = "Sent")]
    Sent,
    #[serde(rename = "Opened")]
    Opened,
    #[serde(rename = "Clicked")]
    Clicked,
    #[serde(rename = "Unsubscribed")]
    Unsubscribed,
    #[serde(rename = "AbuseReport")]
    AbuseReport,

}

impl ToString for LogJobStatus {
    fn to_string(&self) -> String {
        match self {
            Self::All => String::from("All"),
            Self::ReadyToSend => String::from("ReadyToSend"),
            Self::WaitingToRetry => String::from("WaitingToRetry"),
            Self::Sending => String::from("Sending"),
            Self::Error => String::from("Error"),
            Self::Sent => String::from("Sent"),
            Self::Opened => String::from("Opened"),
            Self::Clicked => String::from("Clicked"),
            Self::Unsubscribed => String::from("Unsubscribed"),
            Self::AbuseReport => String::from("AbuseReport"),
        }
    }
}

impl Default for LogJobStatus {
    fn default() -> LogJobStatus {
        Self::All
    }
}




