/*
 * Elastic Email REST API
 *
 * This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    To start using this API, you will need your Access Token (available <a href=\"https://elasticemail.com/account#/settings/new/manage-api\">here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    This is the documentation for REST API. If you’d like to read our legacy documentation regarding Web API v2 click <a href=\"https://api.elasticemail.com/public/help\">here</a>.
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@elasticemail.com
 * Generated by: https://openapi-generator.tech
 */

/// SmtpCredentials : SMTP Credentials info



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SmtpCredentials {
    /// Access level of this Smtp Credential.
    #[serde(rename = "AccessLevel", skip_serializing_if = "Option::is_none")]
    pub access_level: Option<crate::models::AccessLevel>,
    /// Name of the key.
    #[serde(rename = "Name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Date this SmtpCredential was created.
    #[serde(rename = "DateCreated", skip_serializing_if = "Option::is_none")]
    pub date_created: Option<String>,
    /// Date this SmtpCredential was last used.
    #[serde(rename = "LastUse", skip_serializing_if = "Option::is_none")]
    pub last_use: Option<String>,
    /// Date this SmtpCredential expires.
    #[serde(rename = "Expires", skip_serializing_if = "Option::is_none")]
    pub expires: Option<String>,
    /// Which IPs can use this SmtpCredential
    #[serde(rename = "RestrictAccessToIPRange", skip_serializing_if = "Option::is_none")]
    pub restrict_access_to_ip_range: Option<Vec<String>>,
}

impl SmtpCredentials {
    /// SMTP Credentials info
    pub fn new() -> SmtpCredentials {
        SmtpCredentials {
            access_level: None,
            name: None,
            date_created: None,
            last_use: None,
            expires: None,
            restrict_access_to_ip_range: None,
        }
    }
}


