/*
 * Elastic Email REST API
 *
 * This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    To start using this API, you will need your Access Token (available <a href=\"https://elasticemail.com/account#/settings/new/manage-api\">here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    This is the documentation for REST API. If you’d like to read our legacy documentation regarding Web API v2 click <a href=\"https://api.elasticemail.com/public/help\">here</a>.
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@elasticemail.com
 * Generated by: https://openapi-generator.tech
 */

/// SubaccountPayload : New SubAccount payload



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubaccountPayload {
    /// Proper email address.
    #[serde(rename = "Email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    /// Current password.
    #[serde(rename = "Password", skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
    /// True, if you want to send activation email to this Account to confirm the creation of a new SubAccount. Otherwise, false (SubAccount will immediately be Active).
    #[serde(rename = "SendActivation", skip_serializing_if = "Option::is_none")]
    pub send_activation: Option<bool>,
    /// SubAccount settings
    #[serde(rename = "Settings", skip_serializing_if = "Option::is_none")]
    pub settings: Option<crate::models::SubaccountSettingsInfoPayload>,
}

impl SubaccountPayload {
    /// New SubAccount payload
    pub fn new() -> SubaccountPayload {
        SubaccountPayload {
            email: None,
            password: None,
            send_activation: None,
            settings: None,
        }
    }
}


