/*
 * Elastic Email REST API
 *
 * This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    To start using this API, you will need your Access Token (available <a target=\"_blank\" href=\"https://elasticemail.com/account#/settings/new/manage-api\">here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    This is the documentation for REST API. If you’d like to read our legacy documentation regarding Web API v2 click <a target=\"_blank\" href=\"https://api.elasticemail.com/public/help\">here</a>.    Downloadable library clients can be found in our Github repository <a target=\"_blank\" href=\"https://github.com/ElasticEmail?tab=repositories&q=%22rest+api%22+in%3Areadme\">here</a>
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@elasticemail.com
 * Generated by: https://openapi-generator.tech
 */

/// SubaccountEmailCreditsPayload : A change to SubAccount email credits pool, with an additional note.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubaccountEmailCreditsPayload {
    /// Positive or negative value; this will be added or subtracted from Subaccount's current email Credits pool.
    #[serde(rename = "Credits", skip_serializing_if = "Option::is_none")]
    pub credits: Option<i32>,
    /// Note to append to this credits change, for history.
    #[serde(rename = "Notes", skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
}

impl SubaccountEmailCreditsPayload {
    /// A change to SubAccount email credits pool, with an additional note.
    pub fn new() -> SubaccountEmailCreditsPayload {
        SubaccountEmailCreditsPayload {
            credits: None,
            notes: None,
        }
    }
}


