/*
 * Elastic Email REST API
 *
 * This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    To start using this API, you will need your Access Token (available <a href=\"https://elasticemail.com/account#/settings/new/manage-api\">here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    This is the documentation for REST API. If you’d like to read our legacy documentation regarding Web API v2 click <a href=\"https://api.elasticemail.com/public/help\">here</a>.
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@elasticemail.com
 * Generated by: https://openapi-generator.tech
 */

/// Template : Template info



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Template {
    /// How the template should be edited
    #[serde(rename = "TemplateType", skip_serializing_if = "Option::is_none")]
    pub template_type: Option<crate::models::TemplateType>,
    /// Template name
    #[serde(rename = "Name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Date of creation in YYYY-MM-DDThh:ii:ss format
    #[serde(rename = "DateAdded", skip_serializing_if = "Option::is_none")]
    pub date_added: Option<String>,
    /// Default subject of email.
    #[serde(rename = "Subject", skip_serializing_if = "Option::is_none")]
    pub subject: Option<String>,
    /// Email content of this template
    #[serde(rename = "Body", skip_serializing_if = "Option::is_none")]
    pub body: Option<Vec<crate::models::BodyPart>>,
    /// Visibility of a template
    #[serde(rename = "TemplateScope", skip_serializing_if = "Option::is_none")]
    pub template_scope: Option<crate::models::TemplateScopeType>,
}

impl Template {
    /// Template info
    pub fn new() -> Template {
        Template {
            template_type: None,
            name: None,
            date_added: None,
            subject: None,
            body: None,
            template_scope: None,
        }
    }
}


