/*
 * Elastic Email REST API
 *
 * This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    The API has a limit of 20 concurrent connections and a hard timeout of 600 seconds per request.    To start using this API, you will need your Access Token (available <a target=\"_blank\" href=\"https://elasticemail.com/account#/settings/new/manage-api\">here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    Downloadable library clients can be found in our Github repository <a target=\"_blank\" href=\"https://github.com/ElasticEmail?tab=repositories&q=%22rest+api%22+in%3Areadme\">here</a>
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@elasticemail.com
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TemplateType {
    #[serde(rename = "RawHTML")]
    RawHTML,
    #[serde(rename = "DragDropEditor")]
    DragDropEditor,
    #[serde(rename = "LandingPageEditor")]
    LandingPageEditor,

}

impl ToString for TemplateType {
    fn to_string(&self) -> String {
        match self {
            Self::RawHTML => String::from("RawHTML"),
            Self::DragDropEditor => String::from("DragDropEditor"),
            Self::LandingPageEditor => String::from("LandingPageEditor"),
        }
    }
}

impl Default for TemplateType {
    fn default() -> TemplateType {
        Self::RawHTML
    }
}




