/*
 * Elastic Email REST API
 *
 * This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    The API has a limit of 20 concurrent connections and a hard timeout of 600 seconds per request.    To start using this API, you will need your Access Token (available <a target='_blank' href='https://app.elasticemail.com/marketing/settings/new/manage-api'>here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    Downloadable library clients can be found in our Github repository <a target='_blank' href='https://github.com/ElasticEmail?tab=repositories&q=%22rest+api%22+in%3Areadme'>here</a>
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@elasticemail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WebhookUpdatePayload : Update webhook payload
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookUpdatePayload {
    /// Filename
    #[serde(rename = "Name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// URL of notification.
    #[serde(rename = "URL", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(rename = "NotifyOncePerEmail", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub notify_once_per_email: Option<Option<bool>>,
    #[serde(rename = "NotificationForSent", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub notification_for_sent: Option<Option<bool>>,
    #[serde(rename = "NotificationForOpened", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub notification_for_opened: Option<Option<bool>>,
    #[serde(rename = "NotificationForClicked", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub notification_for_clicked: Option<Option<bool>>,
    #[serde(rename = "NotificationForUnsubscribed", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub notification_for_unsubscribed: Option<Option<bool>>,
    #[serde(rename = "NotificationForAbuseReport", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub notification_for_abuse_report: Option<Option<bool>>,
    #[serde(rename = "NotificationForError", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub notification_for_error: Option<Option<bool>>,
    #[serde(rename = "IsEnabled", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub is_enabled: Option<Option<bool>>,
}

impl WebhookUpdatePayload {
    /// Update webhook payload
    pub fn new() -> WebhookUpdatePayload {
        WebhookUpdatePayload {
            name: None,
            url: None,
            notify_once_per_email: None,
            notification_for_sent: None,
            notification_for_opened: None,
            notification_for_clicked: None,
            notification_for_unsubscribed: None,
            notification_for_abuse_report: None,
            notification_for_error: None,
            is_enabled: None,
        }
    }
}

